### ISSUE TITLE
Windwalker not checking for WhirlingDragonPunch presence

### ISSUE THREAD

**Issue by aneri90** [kaminaris/MaxDps-Monk#1]
Hey in main.lua line 270 we need to check for talents[WW.WhirlingDragonPunch].
Otherwise it will try to make me do a spell even if I havent talented it.

I can make you a pull request if you dont have time.
Bye!

**Comment by pwilkowski** [comment]
I usually have time at weekend so feel free to make PRs, will be faster but if you find a bug like this, you need to check whole code if there are no more occurances. In this case it was also around like 156:
https://github.com/kaminaris/MaxDps-Monk/commit/8a6a2f4cb439cc7e64a1847ce21a1bcb2e2049d2

So it was fixed and pushed.
